#server.port=8081

spring.application.name=MqttListener
mqtt.url=tcp://192.168.1.14:1883
mqtt.client.id=spring-mqtt-listener
mqtt.topic=sensores/#

spring.datasource.url=jdbc:postgresql://192.168.1.4:5432/sensordb
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

logging.pattern.console=%-5level%msg%n
